name: GitHub Repository--Terraform-Apply
on:
  workflow_dispatch:

env:
  aws-region: us-east-1
  aws_s3_bucket: priyanka-backend-bucket
  tfstate_file: terraState.tfstate
  db_table: priyanka-dynamo-table

jobs:
  terraformInit:
    name: terraInit
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Terraform HasiCorp SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      # - name: Git global configure
      #   uses: actions/labeler@v4
      #   with:
      #     repo-token: ${{ secrets.PAT_TOKEN }}
       
      - name: terraform format
        run: 
          terraform fmt
      
      - name: terraform init
        run: 
          terraform init -reconfigure -backend-config="bucket=$aws_s3_bucket" -backend-config="key=$tfstate_file" -backend-config="dynamodb_table=$db_table"

      - name: terraform validate
        run: 
          terraform validate

      - name: terraform plan
        run: 
          terraform plan

      - name: terraform apply
        run: 
          terraform apply -auto-approve 
      
      - name: Show state file content after apply
        run:
          cat $tfstate_file